### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ErnandoR** [jonalan7/Hydra-bot#111]
interfaceChange:  {
  onType: 'interfaceChange',
  session: 'session',
  result: { displayInfo: 'CONNECTING', mode: 'QR', info: 'SYNCING' }
}
interfaceChange:  {
  onType: 'interfaceChange',
  session: 'session',
  result: { displayInfo: 'CONNECTING', mode: 'SYNCING', info: 'NORMAL' }
}
interfaceChange:  {
  onType: 'interfaceChange',
  session: 'session',
  result: { displayInfo: 'CONNECTING', mode: 'QR', info: 'OPENING' }
}
interfaceChange:  {
  onType: 'interfaceChange',
  session: 'session',
  result: { displayInfo: 'CONNECTING', mode: 'QR', info: 'PAIRING' }
}
interfaceChange:  {
  onType: 'interfaceChange',
  session: 'session',
  result: { displayInfo: 'CONNECTING', mode: 'QR', info: 'NORMAL' }
}
info Browser:  Auto close called!

**Comment by ErnandoR** [comment]
stop working after Auto close called!

**Comment by jonalan7** [comment]
to be able to stop automatic closing you can use the following option:
  {
  timeAutoClose: 0, // If you don't read the QR CODE by default 60 seconds, it will automatically close the client's browser to save memory, if you want to disable it, set 0 or false
  }
