### ISSUE TITLE
Does this library keep session for long term?

### ISSUE THREAD

**Issue by roysG** [jonalan7/Hydra-bot#39]
Hi,
I am using in some library that also allow to send msg to users.
But there is a bug in the library i am using, after some times unexpected the session can׳t be loaded and i need to remove the folder and scan the qr code from start.

Is this bug happen in your library?

It also important to mention that i am using in pm2.

Second thing, Is this library considiring to be updated when whatsapp makes updates and sometime broken the library?

**Comment by jonalan7** [comment]
This problem has been fixed here! You don't have to worry about the token folder!

**Comment by jonalan7** [comment]
This project has business support! With more than 30 thousand customers.

**Comment by roysG** [comment]
Thanks for your answers,
What do you mean business support, does it free?

**Comment by jonalan7** [comment]
This project is funded! By these companies:
![image](https://user-images.githubusercontent.com/67329824/179265046-f1ddc84e-28d5-41d2-832d-9baee5589805.png)

**Comment by roysG** [comment]
Sound great, later i will try this library and updated!
