### ISSUE TITLE
Docker and Database

### ISSUE THREAD

**Issue by chrisk8er** [jonalan7/Hydra-bot#45]
I'm having trouble saving the user I created when using docker. Docker will reset the data when I stop the container.
any solution to store the database outside docker?

**Comment by jonalan7** [comment]
Be more specific, not understood very well. Make your question better!

**Comment by chrisk8er** [comment]
> Be more specific, not understood very well. Make your question better!

Sorry for that, I just updated my question.

**Comment by chrisk8er** [comment]
Hi @jonalan7, I just noticed that you used SQLite for saving the user data at `node_modules/hydra-bot/dist/ws/lessons/lessons.db3`.
This will be a problem if I use Docker and redownload the node libraries. All saved data will be lost.
